### PR TITLE
Fixed Destroy and changed json layout

### PR DESCRIPTION
**Pull request by Viproz**
Fixed the destroy issue
Changed the json layout to fully use json
Fixed fadeout not fading out children objects
Using transform childs to be able to add UI elements to already existing UI
You can now delete or set parent to an element of UI using a path like "TestPanel7766/Button"

### CODE REVIEW

**Comment by ZuenTheMan** [comment]
I checked your code and I saw some issues. I just read through them and have not tested them.

Looking at your method
recursiveAddUI(JSON.Object json, GameObject parent)

you can not destroy the gameobject just because it have the same name. Some people only name their main UI and the rest gets named "AddUI CreatedPanel" by default. yet in the code below you basically destroy the other created gameobjects?

//Add the GameObject to serverCreatedUI since it's a new UI and destroy old one if it exists
if(go != null)
      DestroyPanel(go.name, true);

also DestroyImmediate()  method seems to be missing?

**Comment by Viproz** [comment]
Only the main panel name have to be unique and gets added to the list, the other ones are just stored as child in the transform
What about the DestroyImmediate() missing ?

**Comment by ZuenTheMan** [comment]
I forgot "DestroyImmediate" is a Unity method. Apologies on that.

I still dislike the json structure. It's not flexible as the original one and everyone that is creating UI's already knows the existing structure. You are also limiting them from having to re-create the whole UI just if a child UI value has been changed.

**Comment by Viproz** [comment]
As I said in the PR no I am not limiting them to recreating the UI to change a value, if you want to replace it you just do : 
 - Call the destroy method with the path to the UI element like for the button text : "TestPanel7766/Button/ButtonText"
 - Call the method AddUI with your json parent set to "TestPanel7766/Button"

**Pull request closed without merging**
